server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dynamic_mock_db
    username: vijay
    password: vijay123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "SET TIME ZONE 'Asia/Kolkata'"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata
    show-sql: true

app:
  jwt:
    # base64 of a 256-bit secret. Replace for production.
    secret: "c3ByaW5nLWJvb3QtZGV2LXNlY3JldC1rZXktMzJieXRlc2Jhc2U2NA=="
    expiration-ms: 86400000
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:5173"

logging:
  level:
    org.hibernate.SQL: WARN
    org.springframework.security: INFO

